//! Image generation DTOs and generator trait.

use std::sync::Arc;

use async_trait::async_trait;
use serde::{Deserialize, Serialize};
use thiserror::Error;

use crate::ModelUsage;

/// Provider-agnostic image generation or edit request.
#[derive(Clone, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
pub struct ImageGenerationRequest {
    /// Text instruction used to generate or edit the image.
    pub prompt: String,
    /// Ordered input images; a non-empty list selects edit mode.
    #[serde(default)]
    pub input_images: Vec<ImageGenerationInputImage>,
    /// Best-effort output aspect.
    #[serde(default)]
    pub aspect: ImageGenerationAspect,
    /// Best-effort output quality.
    #[serde(default)]
    pub quality: ImageGenerationQuality,
}

/// Decoded image supplied as edit context.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct ImageGenerationInputImage {
    /// Encoded image file bytes.
    pub data: Vec<u8>,
    /// MIME media type describing the image bytes.
    pub mime_type: String,
}

/// Provider-agnostic image aspect preference.
#[derive(Clone, Copy, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum ImageGenerationAspect {
    /// Let the provider select the output aspect.
    #[default]
    Auto,
    /// Prefer a square output.
    Square,
    /// Prefer a landscape output.
    Landscape,
    /// Prefer a portrait output.
    Portrait,
}

/// Provider-agnostic image quality preference.
#[derive(Clone, Copy, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum ImageGenerationQuality {
    /// Let the provider select the output quality.
    #[default]
    Auto,
    /// Prefer the provider's low-quality mode.
    Low,
    /// Prefer the provider's medium-quality mode.
    Medium,
    /// Prefer the provider's high-quality mode.
    High,
}

/// One generated image with its encoded file bytes and media type.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct GeneratedImage {
    /// Encoded generated image file bytes.
    pub data: Vec<u8>,
    /// MIME media type describing the generated bytes.
    pub mime_type: String,
}

/// Normalized response from one image generation call.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct ImageGenerationResponse {
    /// Provider that generated the image.
    pub provider: String,
    /// Configured provider model identifier.
    pub model_id: String,
    /// Exactly one generated image.
    pub image: GeneratedImage,
    /// Provider-revised prompt when one was reported.
    pub revised_prompt: Option<String>,
    /// Provider-reported normalized token usage.
    pub usage: ModelUsage,
}

/// Errors returned by the image generation boundary.
#[derive(Debug, Error)]
pub enum ImageGenerationError {
    /// The client submitted a blank prompt.
    #[error("[ai_interface/image_generator] prompt must not be empty")]
    EmptyPrompt,
    /// An input image used an unsupported MIME media type.
    #[error("[ai_interface/image_generator] unsupported media type `{content_type}`")]
    UnsupportedMediaType {
        /// Unsupported MIME media type.
        content_type: String,
    },
    /// The provider refused the request due to content policy.
    #[error(
        "[ai_interface/image_generator] content policy refusal for `{provider}` model `{model_id}`: {message}"
    )]
    ContentPolicy {
        /// Provider that refused the request.
        provider: String,
        /// Requested provider model identifier.
        model_id: String,
        /// Provider-supplied refusal details.
        message: String,
    },
    /// The provider returned no final image.
    #[error("[ai_interface/image_generator] no image returned by `{provider}` model `{model_id}`")]
    NoImage {
        /// Provider that returned no final image.
        provider: String,
        /// Requested provider model identifier.
        model_id: String,
    },
    /// The provider rejected the request due to a rate limit.
    #[error(
        "[ai_interface/image_generator] provider rate limit for `{provider}` model `{model_id}`: {message}"
    )]
    RateLimited {
        /// Provider that returned the rate limit.
        provider: String,
        /// Requested provider model identifier.
        model_id: String,
        /// Provider-supplied failure details.
        message: String,
    },
    /// The provider returned a transient failure that may succeed later.
    #[error(
        "[ai_interface/image_generator] transient provider failure for `{provider}` model `{model_id}`: {message}"
    )]
    TransientProvider {
        /// Provider that returned the transient failure.
        provider: String,
        /// Requested provider model identifier.
        model_id: String,
        /// Provider-supplied failure details.
        message: String,
    },
    /// The provider returned a non-retryable failure.
    #[error(
        "[ai_interface/image_generator] provider failure for `{provider}` model `{model_id}`: {message}"
    )]
    Provider {
        /// Provider that returned the failure.
        provider: String,
        /// Requested provider model identifier.
        model_id: String,
        /// Provider-supplied failure details.
        message: String,
    },
    /// Unhandled image-generation-boundary failure.
    #[error("[ai_interface/image_generator] internal error: {source}")]
    Internal {
        /// Underlying local failure.
        source: Box<dyn std::error::Error + Send + Sync>,
    },
}

impl ImageGenerationError {
    /// Builds an unsupported media type error.
    pub fn unsupported_media_type(content_type: impl Into<String>) -> Self {
        Self::UnsupportedMediaType {
            content_type: content_type.into(),
        }
    }

    /// Builds a content-policy refusal.
    pub fn content_policy(
        provider: impl Into<String>,
        model_id: impl Into<String>,
        message: impl Into<String>,
    ) -> Self {
        Self::ContentPolicy {
            provider: provider.into(),
            model_id: model_id.into(),
            message: message.into(),
        }
    }

    /// Builds a no-image provider response error.
    pub fn no_image(provider: impl Into<String>, model_id: impl Into<String>) -> Self {
        Self::NoImage {
            provider: provider.into(),
            model_id: model_id.into(),
        }
    }

    /// Builds a rate-limited provider error.
    pub fn rate_limited(
        provider: impl Into<String>,
        model_id: impl Into<String>,
        message: impl Into<String>,
    ) -> Self {
        Self::RateLimited {
            provider: provider.into(),
            model_id: model_id.into(),
            message: message.into(),
        }
    }

    /// Builds a transient provider error.
    pub fn transient_provider(
        provider: impl Into<String>,
        model_id: impl Into<String>,
        message: impl Into<String>,
    ) -> Self {
        Self::TransientProvider {
            provider: provider.into(),
            model_id: model_id.into(),
            message: message.into(),
        }
    }

    /// Builds a non-retryable provider error.
    pub fn provider(
        provider: impl Into<String>,
        model_id: impl Into<String>,
        message: impl Into<String>,
    ) -> Self {
        Self::Provider {
            provider: provider.into(),
            model_id: model_id.into(),
            message: message.into(),
        }
    }

    /// Wraps an internal image-generation-boundary error.
    pub fn internal(source: impl std::error::Error + Send + Sync + 'static) -> Self {
        Self::Internal {
            source: Box::new(source),
        }
    }
}

/// Result alias for image generation operations.
pub type ImageGenerationResult<T> = std::result::Result<T, ImageGenerationError>;

#[cfg_attr(
    any(test, doctest, feature = "test-support"),
    unimock::unimock(api = ImageGeneratorMock)
)]
#[async_trait]
/// Provider-agnostic image generation and editing boundary.
pub trait ImageGenerator: Send + Sync {
    /// Generates or edits exactly one image.
    async fn generate(
        &self,
        request: &ImageGenerationRequest,
    ) -> ImageGenerationResult<ImageGenerationResponse>;
}

/// Shared dynamic image generator alias.
pub type DynImageGenerator = Arc<dyn ImageGenerator>;
