//! Video generation DTOs and generator trait.

use std::sync::Arc;

use async_trait::async_trait;
use internal_error::InternalError;
use serde::{Deserialize, Serialize};
use thiserror::Error;

use crate::ModelUsage;

/// Provider-agnostic video generation request.
#[derive(Clone, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
pub struct VideoGenerationRequest {
    /// Text instruction used to generate the video.
    pub prompt: String,
    /// Optional image used as the video's first frame.
    #[serde(default)]
    pub input_image: Option<VideoGenerationInputImage>,
    /// Portable output aspect.
    #[serde(default)]
    pub aspect: VideoGenerationAspect,
    /// Portable output duration.
    #[serde(default)]
    pub duration: VideoGenerationDuration,
    /// Portable output resolution.
    #[serde(default)]
    pub resolution: VideoGenerationResolution,
}

/// Decoded image supplied as a first-frame constraint.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct VideoGenerationInputImage {
    /// Encoded image file bytes.
    pub data: Vec<u8>,
    /// MIME media type describing the image bytes.
    pub mime_type: String,
}

/// Portable video aspect preference.
#[derive(Clone, Copy, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum VideoGenerationAspect {
    /// Generate a 16:9 video.
    #[default]
    Landscape,
    /// Generate a 9:16 video.
    Portrait,
}

/// Portable video duration.
#[derive(Clone, Copy, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum VideoGenerationDuration {
    /// Generate a four-second video.
    #[default]
    Seconds4,
    /// Generate an eight-second video.
    Seconds8,
}

impl VideoGenerationDuration {
    /// Returns the represented duration in seconds.
    pub fn seconds(self) -> u8 {
        match self {
            Self::Seconds4 => 4,
            Self::Seconds8 => 8,
        }
    }
}

/// Portable video output resolution.
#[derive(Clone, Copy, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum VideoGenerationResolution {
    /// Generate a 720p video.
    #[default]
    P720,
}

/// One generated video with encoded file bytes and metadata.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct GeneratedVideo {
    /// Encoded generated video file bytes.
    pub data: Vec<u8>,
    /// MIME media type describing the generated bytes.
    pub mime_type: String,
    /// Duration of the generated clip in seconds.
    pub duration_seconds: u8,
    /// Encoded frame width in pixels.
    pub width: u16,
    /// Encoded frame height in pixels.
    pub height: u16,
}

/// Normalized response from one video generation call.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct VideoGenerationResponse {
    /// Provider that generated the video.
    pub provider: String,
    /// Configured provider model identifier.
    pub model_id: String,
    /// Exactly one generated video.
    pub video: GeneratedVideo,
    /// Provider-reported normalized usage.
    pub usage: ModelUsage,
}

/// Errors returned by the video generation boundary.
#[derive(Debug, Error, internal_error::ErrorContract)]
pub enum VideoGenerationError {
    /// The client submitted a blank prompt.
    #[error("[ai_interface/video_generator] prompt must not be empty")]
    EmptyPrompt,
    /// An input image used an unsupported MIME media type.
    #[error("[ai_interface/video_generator] unsupported media type `{content_type}`")]
    UnsupportedMediaType {
        /// Unsupported MIME media type.
        content_type: String,
    },
    /// The provider refused the request due to content policy.
    #[error(
        "[ai_interface/video_generator] content policy refusal for `{provider}` model `{model_id}`: {message}"
    )]
    ContentPolicy {
        /// Provider that refused the request.
        provider: String,
        /// Requested provider model identifier.
        model_id: String,
        /// Provider-supplied refusal details.
        message: String,
    },
    /// The provider returned no final video.
    #[error("[ai_interface/video_generator] no video returned by `{provider}` model `{model_id}`")]
    NoVideo {
        /// Provider that returned no final video.
        provider: String,
        /// Requested provider model identifier.
        model_id: String,
    },
    /// The provider did not complete before the configured deadline.
    #[error(
        "[ai_interface/video_generator] generation timed out for `{provider}` model `{model_id}`"
    )]
    TimedOut {
        /// Provider whose job timed out.
        provider: String,
        /// Requested provider model identifier.
        model_id: String,
    },
    /// The provider rejected the request due to a rate limit.
    #[error(
        "[ai_interface/video_generator] provider rate limit for `{provider}` model `{model_id}`: {message}"
    )]
    RateLimited {
        /// Provider that returned the rate limit.
        provider: String,
        /// Requested provider model identifier.
        model_id: String,
        /// Provider-supplied failure details.
        message: String,
    },
    /// The provider returned a transient failure that may succeed later.
    #[error(
        "[ai_interface/video_generator] transient provider failure for `{provider}` model `{model_id}`: {message}"
    )]
    TransientProvider {
        /// Provider that returned the transient failure.
        provider: String,
        /// Requested provider model identifier.
        model_id: String,
        /// Provider-supplied failure details.
        message: String,
    },
    /// The provider returned a non-retryable failure.
    #[error(
        "[ai_interface/video_generator] provider failure for `{provider}` model `{model_id}`: {message}"
    )]
    Provider {
        /// Provider that returned the failure.
        provider: String,
        /// Requested provider model identifier.
        model_id: String,
        /// Provider-supplied failure details.
        message: String,
    },
    /// Unhandled video-generation-boundary failure.
    #[error("[ai_interface/video_generator] internal error")]
    Internal(#[from] InternalError),
}

impl VideoGenerationError {
    /// Builds an unsupported media type error.
    pub fn unsupported_media_type(content_type: impl Into<String>) -> Self {
        Self::UnsupportedMediaType {
            content_type: content_type.into(),
        }
    }

    /// Builds a content-policy refusal.
    pub fn content_policy(
        provider: impl Into<String>,
        model_id: impl Into<String>,
        message: impl Into<String>,
    ) -> Self {
        Self::ContentPolicy {
            provider: provider.into(),
            model_id: model_id.into(),
            message: message.into(),
        }
    }

    /// Builds a no-video provider response error.
    pub fn no_video(provider: impl Into<String>, model_id: impl Into<String>) -> Self {
        Self::NoVideo {
            provider: provider.into(),
            model_id: model_id.into(),
        }
    }

    /// Builds a generation-timeout error.
    pub fn timed_out(provider: impl Into<String>, model_id: impl Into<String>) -> Self {
        Self::TimedOut {
            provider: provider.into(),
            model_id: model_id.into(),
        }
    }

    /// Builds a rate-limited provider error.
    pub fn rate_limited(
        provider: impl Into<String>,
        model_id: impl Into<String>,
        message: impl Into<String>,
    ) -> Self {
        Self::RateLimited {
            provider: provider.into(),
            model_id: model_id.into(),
            message: message.into(),
        }
    }

    /// Builds a transient provider error.
    pub fn transient_provider(
        provider: impl Into<String>,
        model_id: impl Into<String>,
        message: impl Into<String>,
    ) -> Self {
        Self::TransientProvider {
            provider: provider.into(),
            model_id: model_id.into(),
            message: message.into(),
        }
    }

    /// Builds a non-retryable provider error.
    pub fn provider(
        provider: impl Into<String>,
        model_id: impl Into<String>,
        message: impl Into<String>,
    ) -> Self {
        Self::Provider {
            provider: provider.into(),
            model_id: model_id.into(),
            message: message.into(),
        }
    }
}

/// Result alias for video generation operations.
pub type VideoGenerationResult<T> = std::result::Result<T, VideoGenerationError>;

#[cfg_attr(
    any(test, doctest, feature = "test-support"),
    unimock::unimock(api = VideoGeneratorMock)
)]
#[async_trait]
/// Provider-agnostic video generation boundary.
pub trait VideoGenerator: Send + Sync {
    /// Generates and downloads exactly one video.
    async fn generate(
        &self,
        request: &VideoGenerationRequest,
    ) -> VideoGenerationResult<VideoGenerationResponse>;
}

/// Shared dynamic video generator alias.
pub type DynVideoGenerator = Arc<dyn VideoGenerator>;
